# Setup
<<<<<<< HEAD
title: Jamie Ryan
tagline: "Software Developer"
description: "Ruminations on the world of technology."
url: https://mrjamieryan.github.io
baseurl: ""
paginate: 10
=======
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://hyde.getpoole.com
baseurl:          ''
paginate:         5
>>>>>>> parent of de5e13a... V3

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
