# Setup
title: Jamie Ryan
tagline: "Software Developer"
description: "Strongly Typed and Opinionated"
url: https://mrjamieryan.github.io
baseurl: "/"
paginate: 10

# About and contact
author:
  name: "Jamie Ryan"
  url: https://twitter.com/jamieryandev

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
