# Setup
title: Jamie Ryan
tagline: "Software Developer"
description: "Ruminations on the world of technology."
url: https://mrjamieryan.github.io
baseurl: ""
paginate: 10

# About and contact
author:
  name: "Jamie Ryan"
  url: https://twitter.com/jamieryandev

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version: 3.0.0
