# Dependencies
markdown: kramdown
highlighter:  pygments

# Permalinks
permalink: pretty

# Setup
title: Jamie Ryan
tagline: 'Software Developer'
description: 'Ruminations on the world of technology
url: http://jamieryan.dev
baseurl: /

author:
  name: 'Jamie Ryan'
  url: https://twitter.com/jamieryandev

paginate: 10

# Custom vars
version: 2.1.0

github: https://github.com/mrjamieryan
  repo: https://github.com/mrjamieryan
