# Setup
title: Loosely Typed
tagline: "and opinionated"
description: "...and opinionated"
url: https://looselytyped.co.uk
baseurl: "/"
paginate: 10

# About and contact
author:
  name: "Jamie Ryan"
  url: https://twitter.com/jamieryandev

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
