# Setup
title: Jamie Ryan
tagline: "Software Developer"
description: "Ruminations on the modern world of technology"
url: https://mrjamieryan.github.io
baseurl: "https://mrjamieryan.github.io"
paginate: 10

# About and contact
author:
  name: "Jamie Ryan"
  url: https://twitter.com/jamieryandev

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
